General: 
  nTimesteps: 24 # number of timesteps per representative day
  nReprDays: 8 # days
  nDays: 365 # days
  nYears: 9 # years
  totConsumers: 1000000 #  1 million consumers
  beta: 0.2 # fraction of tail risk (the 'unconfidence' level)
  gamma: 0.5 # weight of risk-aversion [0 = very risk averse, 1 = risk neutral]

ADMM:
 rho_EOM: 0.01 # rho ADMM penalty term, EOM (10^6 €/GWh) 10 €/MWh
 max_iter: 1000 # maximum number of iterations
 epsilon: 0.01 # stopping criterion - tolerance on "accuracy" with which the coupling constraints are satisfied. Applied to dual and primal residuals. # GWh
 CircularBufferSize: 2 # number of iterations for which data will be retained, should be at least 2 and less than max_iter

cfd:
  lambda_cfd: 0.08 # 10^6 €/GWh # 70 €/MWh
  rho_cfd: 0.01 # rho penalty term, cfd (10^6 €/GW) 10€/MW
  epsilon_cfd: 0.01 # stopping criterion - tolerance on "accuracy" with which the coupling constraints are satisfied. Applied to dual and primal residuals.

Consumers: # Set of representative consumers
  TypeA: # WEALTHY CONSUMER
   Share: 0.25 # Share of consumers in overall consumer mix
   PV_cap: 0.000003 #GWp 3 kWp
   D: "CONS_HIGH" # GWh Demand timeseries that needs to be picked up
   PV_AF: "SOLAR_WEST" # GWp AF solar timeseries that needs to be picked up
   WTP: 5 # (10^6 €/GWh) 5000 (€/MWh)
   Battery:
    cap_smax: 0.000015 # GWh (15 kWh)
    EC: 0.9
    ED: 0.9
    Decay: 0.9999
    winj: 0.000005 # GW 5kW
    wwith: 0.000005 # GW 5kW

  TypeB: # WEALTHY, WITHOUT FLEX
   Share: 0.25  # Share of consumers in overall consumer mix
   #PV_cap: 0.000003 # GWp 3 kWp
   D: "CONS_HIGH" # Timeseries that needs to be picked up
   #PV_AF: "SOLAR_WEST" # AF solar timeseries that needs to be picked up
   WTP: 5 # 10^6 €/GW 2500 €/MWh

  TypeC: # POOR WITH FLEX
   Share: 0.25  # Share of consumers in overall consumer mix
   PV_cap: 0.000003 # GWp 3 kWp
   D: "CONS_LOW" # Timeseries that needs to be picked up
   PV_AF: "SOLAR_WEST" # AF solar timeseries that needs to be picked up
   WTP: 1 # 10^6 €/GWh (1000 €/MWh)
   Battery:
    cap_smax: 0.000015 # GWh (15 kWh)
    EC: 0.9
    ED: 0.9
    Decay: 0.9999
    winj: 0.000005 # GW 5kW
    wwith: 0.000005 # GW 5kW

  TypeD: # POOR WITHOUT FLEX
   Share: 0.25
   #PV_cap: 0 # NO PV!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   D: "CONS_LOW"
   #PV_AF: "SOLAR_WEST"
   WTP: 1 # 10^6 €/GWh (1000 €/MWh)

Generators:
  Baseload:
    b: 0.01 # 10^6 €/GWh, 10 €/MWh
    C: 5 # GW (5000 MW)

  GasTurbine:
    b: 0.04 # 40 M€/GWh
    C: 5 # GW (5000 MW)

  Peak:
    b: 0.2 # (10^6€/GWh) (200 €/MWh)
    C: 10 # GW (5000 MW)
  
  WindOnshore:
    b: 0 # 10^6 €/GWh ,€/MWh
    C: 5 # GW (5000 MW)
    AF: "WIND_ONSHORE"
  
  WindOffshore:
    b: 0 # 10^6 €/GWh ,€/MWh
    C: 5 # GW (5000 MW)
    AF: "WIND_OFFSHORE"
  
  SolarPanels:
    b: 0 # 10^6 €/GWh, €/MWh
    C: 5 #GW (5000 MW)
    AF: "SOLAR_SOUTH"